#!/usr/bin/env python3
"""Generate the canonical DISKPATH repository manifest.

The manifest describes Git-tracked regular files in the repository.
DISKPATH.json and DISKPATH.md are excluded to avoid self-referential
content and hash instability.

This tool is portable across Linux, macOS, Windows, and Codespaces.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import subprocess
import sys
from pathlib import Path


SCHEMA_VERSION = 1
GENERATOR_NAME = "phakphum-calendar-diskpath"
GENERATOR_VERSION = "1.0.0"

MANIFEST_JSON = Path("DISKPATH.json")
MANIFEST_MD = Path("DISKPATH.md")

EXCLUDED_PATHS = (
    "DISKPATH.json",
    "DISKPATH.md",
)

CHUNK_SIZE = 1024 * 1024


def repository_root() -> Path:
    result = subprocess.run(
        ["git", "rev-parse", "--show-toplevel"],
        check=True,
        capture_output=True,
        text=True,
    )
    return Path(result.stdout.strip()).resolve()


def tracked_paths(root: Path) -> list[str]:
    result = subprocess.run(
        ["git", "ls-files", "-z"],
        cwd=root,
        check=True,
        capture_output=True,
    )

    paths = result.stdout.decode("utf-8").split("\0")

    return sorted(
        path
        for path in paths
        if path
        and path not in EXCLUDED_PATHS
        and (root / path).is_file()
    )


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()

    with path.open("rb") as handle:
        while True:
            chunk = handle.read(CHUNK_SIZE)
            if not chunk:
                break
            digest.update(chunk)

    return digest.hexdigest()


def build_manifest(root: Path) -> dict:
    files = []

    for relative_path in tracked_paths(root):
        absolute_path = root / relative_path

        files.append(
            {
                "path": relative_path,
                "size": absolute_path.stat().st_size,
                "sha256": sha256_file(absolute_path),
            }
        )

    return {
        "schema_version": SCHEMA_VERSION,
        "generator": {
            "name": GENERATOR_NAME,
            "version": GENERATOR_VERSION,
        },
        "manifest_scope": "git-tracked-regular-files",
        "excluded_paths": list(EXCLUDED_PATHS),
        "file_count": len(files),
        "files": files,
    }


def render_json(manifest: dict) -> str:
    return json.dumps(
        manifest,
        indent=2,
        ensure_ascii=False,
    ) + "\n"


def render_markdown(manifest: dict) -> str:
    lines = [
        "# DISKPATH",
        "",
        "> Automatically generated repository disk-path manifest. "
        "Do not edit this file manually.",
        "",
        "## Purpose",
        "",
        "This document is generated from the actual repository tree.",
        "",
        "It records:",
        "",
        "- repository-relative file paths",
        "- file size in bytes",
        "- SHA-256 for each file",
        "",
        "This manifest is documentation/evidence only. "
        "It does not define runtime authorization, application behavior, "
        "or deployment policy.",
        "",
        "## Generator",
        "",
        f"- Name: `{manifest['generator']['name']}`",
        f"- Version: `{manifest['generator']['version']}`",
        f"- Schema: `{manifest['schema_version']}`",
        "",
        "## Scope",
        "",
        f"- Manifest scope: `{manifest['manifest_scope']}`",
        f"- Tracked files: `{manifest['file_count']}`",
        "- Excluded paths: "
        + ", ".join(
            f"`{path}`"
            for path in manifest["excluded_paths"]
        ),
        "",
        "## Repository Paths",
        "",
        "| Path | Size (bytes) | SHA-256 |",
        "| --- | ---: | --- |",
    ]

    for entry in manifest["files"]:
        path = entry["path"].replace("|", "\\|")

        lines.append(
            f"| `{path}` | {entry['size']} | `{entry['sha256']}` |"
        )

    lines.extend(
        [
            "",
            "## Integrity",
            "",
            "The canonical machine-readable manifest is `DISKPATH.json`.",
            "",
            "Run `python3 tools/diskpath/validate_diskpath.py` "
            "to validate the manifest against the repository.",
            "",
        ]
    )

    return "\n".join(lines)


def write_if_changed(path: Path, content: str) -> bool:
    if path.exists():
        current = path.read_text(encoding="utf-8")

        if current == content:
            return False

    path.write_text(
        content,
        encoding="utf-8",
        newline="\n",
    )

    return True


def main() -> int:
    parser = argparse.ArgumentParser(
        description="Generate DISKPATH.json and DISKPATH.md."
    )

    parser.add_argument(
        "--check",
        action="store_true",
        help="Fail if generated files are not already current.",
    )

    args = parser.parse_args()

    root = repository_root()

    json_path = root / MANIFEST_JSON
    md_path = root / MANIFEST_MD

    manifest = build_manifest(root)

    json_content = render_json(manifest)
    md_content = render_markdown(manifest)

    if args.check:
        json_current = (
            json_path.exists()
            and json_path.read_text(encoding="utf-8")
            == json_content
        )

        md_current = (
            md_path.exists()
            and md_path.read_text(encoding="utf-8")
            == md_content
        )

        if not json_current or not md_current:
            print("DISKPATH CHECK: FAIL")

            if not json_current:
                print(
                    "- DISKPATH.json is out of date or missing."
                )

            if not md_current:
                print(
                    "- DISKPATH.md is out of date or missing."
                )

            return 1

        print(
            "DISKPATH CHECK: PASS "
            f"({manifest['file_count']} tracked files)"
        )

        return 0

    json_changed = write_if_changed(
        json_path,
        json_content,
    )

    md_changed = write_if_changed(
        md_path,
        md_content,
    )

    print(
        "DISKPATH GENERATION: PASS "
        f"({manifest['file_count']} tracked files)"
    )

    print(
        "DISKPATH.json: "
        f"{'updated' if json_changed else 'current'}"
    )

    print(
        "DISKPATH.md: "
        f"{'updated' if md_changed else 'current'}"
    )

    return 0


if __name__ == "__main__":
    sys.exit(main())
